export const COOKIE_MAX_AGE_1_YEAR = 365 * 24 * 60 * 60

export const maintenanceTypes = [
    "01|UM (Urgent Maintenance)",
    "02|BM (Maintenance Setelah Kejadian)",
    "03|TBC (Periodikal Checking)",
    "04|TBA (Periodikal Maintenance)",
    "05|PvM (Perawatan Pencegahan)",
    "06|FM (Predikisi Maintenance)",
    "07|CM (Corrective Maintenance/RHC)",
    "08|CHECK (Check Tanpa Perencanaan)",
    "09|LAYOUT (Tata Letak)",
];

export const maintenanceCodes = [
    "01|UM",
    "02|BM",
    "03|TBC",
    "04|TBA",
    "05|PvM",
    "06|FM",
    "07|CM",
    "08|CHECK",
    "09|LAYOUT",
];

export const maintenanceNames = [
    "01|Urgent Maintenance",
    "02|Maintenance Setelah Kejadian",
    "03|Periodikal Checking",
    "04|Periodikal Maintenance",
    "05|Perawatan Pencegahan",
    "06|Predikisi Maintenance",
    "07|Corrective Maintenance/RHC",
    "08|Check Tanpa Perencanaan",
    "09|Tata Letak",
];

export const weekOfYear = [
    { id: 1, title: "Jan Week 1" },
    { id: 2, title: "Jan Week 2" },
    { id: 3, title: "Jan Week 3" },
    { id: 4, title: "Jan Week 4" },
    { id: 5, title: "Feb Week 1" },
    { id: 6, title: "Feb Week 2" },
    { id: 7, title: "Feb Week 3" },
    { id: 8, title: "Feb Week 4" },
    { id: 9, title: "Mar Week 1" },
    { id: 10, title: "Mar Week 2" },
    { id: 11, title: "Mar Week 3" },
    { id: 12, title: "Mar Week 4" },
    { id: 13, title: "Apr Week 1" },
    { id: 14, title: "Apr Week 2" },
    { id: 15, title: "Apr Week 3" },
    { id: 16, title: "Apr Week 4" },
    { id: 17, title: "May Week 1" },
    { id: 18, title: "May Week 2" },
    { id: 19, title: "May Week 3" },
    { id: 20, title: "May Week 4" },
    { id: 21, title: "Jun Week 1" },
    { id: 22, title: "Jun Week 2" },
    { id: 23, title: "Jun Week 3" },
    { id: 24, title: "Jun Week 4" },
    { id: 25, title: "Jul Week 1" },
    { id: 26, title: "Jul Week 2" },
    { id: 27, title: "Jul Week 3" },
    { id: 28, title: "Jul Week 4" },
    { id: 29, title: "Aug Week 1" },
    { id: 30, title: "Aug Week 2" },
    { id: 31, title: "Aug Week 3" },
    { id: 32, title: "Aug Week 4" },
    { id: 33, title: "Sep Week 1" },
    { id: 34, title: "Sep Week 2" },
    { id: 35, title: "Sep Week 3" },
    { id: 36, title: "Sep Week 4" },
    { id: 37, title: "Oct Week 1" },
    { id: 38, title: "Oct Week 2" },
    { id: 39, title: "Oct Week 3" },
    { id: 40, title: "Oct Week 4" },
    { id: 41, title: "Nov Week 1" },
    { id: 42, title: "Nov Week 2" },
    { id: 43, title: "Nov Week 3" },
    { id: 44, title: "Nov Week 4" },
    { id: 45, title: "Dec Week 1" },
    { id: 46, title: "Dec Week 2" },
    { id: 47, title: "Dec Week 3" },
    { id: 48, title: "Dec Week 4" },
]
